#!/bin/bash

# *************************************************************
# This function redirect the pipe input to STDERR.
#
# @param stream
# @return string
#
function STDERR () {
  cat - 1>&2
}

error_detected=false
if [ -z "$MAIL_SERVER" ]; then
    echo "Set a \$MAIL_SERVER or you can't loot." | STDERR
    error_detected=true
fi

if [ -z "$LOOTER_NAME" ]; then
    echo "Set a \$LOOTER_NAME or you can't loot." | STDERR
    error_detected=true
fi

if [ -z "$LOOTER_EMAIL" ]; then
    echo "Set a \$LOOTER_EMAIL or you can't loot." | STDERR
    error_detected=true
fi

if [ -z "$LOOT_CONTROLLER_EMAIL" ]; then
    echo "Set a \$LOOT_CONTROLLER_EMAIL or you can't loot." | STDERR
    error_detected=true
fi

if $error_detected; then
    echo "Terminating...!" | STDERR
    exit;
fi

echo "Looting a parking space for you $LOOTER_NAME"
python ./looter.py
